//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Quality.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Quality.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actas del Comité de Calidad.
        /// </summary>
        internal static string ACTA_COMITE {
            get {
                return ResourceManager.GetString("ACTA_COMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Acta del Comité de Calidad:.
        /// </summary>
        internal static string ACTA_COMITE_ADD_TITLE {
            get {
                return ResourceManager.GetString("ACTA_COMITE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Acta del Comité de Calidad:.
        /// </summary>
        internal static string ACTA_COMITE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ACTA_COMITE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Actas del Comité de Calidad:.
        /// </summary>
        internal static string ACTA_COMITE_FIND_TITLE {
            get {
                return ResourceManager.GetString("ACTA_COMITE_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Área:.
        /// </summary>
        internal static string AREA_ADD_TITLE {
            get {
                return ResourceManager.GetString("AREA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Área:.
        /// </summary>
        internal static string AREA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("AREA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizar Área:.
        /// </summary>
        internal static string AREA_FIND_TITLE {
            get {
                return ResourceManager.GetString("AREA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas.
        /// </summary>
        internal static string AREAS {
            get {
                return ResourceManager.GetString("AREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partes de Asistencia.
        /// </summary>
        internal static string ASISTENCIAS {
            get {
                return ResourceManager.GetString("ASISTENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditorías.
        /// </summary>
        internal static string AUDITORIA {
            get {
                return ResourceManager.GetString("AUDITORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Auditoría:.
        /// </summary>
        internal static string AUDITORIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("AUDITORIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Auditoría:.
        /// </summary>
        internal static string AUDITORIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("AUDITORIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Auditorías:.
        /// </summary>
        internal static string AUDITORIA_FIND_TITLE {
            get {
                return ResourceManager.GetString("AUDITORIA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Capacidad:.
        /// </summary>
        internal static string CAPACIDAD_TITLE {
            get {
                return ResourceManager.GetString("CAPACIDAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases de Auditorías.
        /// </summary>
        internal static string CLASE_AUDITORIA {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Clase de Auditoría:.
        /// </summary>
        internal static string CLASE_AUDITORIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Clase de Auditoría:.
        /// </summary>
        internal static string CLASE_AUDITORIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Clases de Auditorías:.
        /// </summary>
        internal static string CLASE_AUDITORIA_FIND_TITLE {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicado de Auditoría.
        /// </summary>
        internal static string COMUNICADO_AUDITORIA_TITLE {
            get {
                return ResourceManager.GetString("COMUNICADO_AUDITORIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concesión de Ampliación:.
        /// </summary>
        internal static string CONCESION_AMPLIACION_TITLE {
            get {
                return ResourceManager.GetString("CONCESION_AMPLIACION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Departamento:.
        /// </summary>
        internal static string DEPARTAMENTO_ADD_TITLE {
            get {
                return ResourceManager.GetString("DEPARTAMENTO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Departamento:.
        /// </summary>
        internal static string DEPARTAMENTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("DEPARTAMENTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Departamentos:.
        /// </summary>
        internal static string DEPARTAMENTO_FIND_TITLE {
            get {
                return ResourceManager.GetString("DEPARTAMENTO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamentos:.
        /// </summary>
        internal static string DEPARTAMENTOS {
            get {
                return ResourceManager.GetString("DEPARTAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancias:.
        /// </summary>
        internal static string DISCREPANCIA_TITLE {
            get {
                return ResourceManager.GetString("DISCREPANCIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Incidencia.
        /// </summary>
        internal static string INCIDENCIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("INCIDENCIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la Incidencia.
        /// </summary>
        internal static string INCIDENCIA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("INCIDENCIA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Incidencia.
        /// </summary>
        internal static string INCIDENCIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("INCIDENCIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Acciones Correctoras:.
        /// </summary>
        internal static string INFORME_ACCION_CORRECTORA_TITLE {
            get {
                return ResourceManager.GetString("INFORME_ACCION_CORRECTORA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Ampliación:.
        /// </summary>
        internal static string INFORME_AMPLIACION_TITLE {
            get {
                return ResourceManager.GetString("INFORME_AMPLIACION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Discrepancias:.
        /// </summary>
        internal static string INFORME_DISCREPANCIA_TITLE {
            get {
                return ResourceManager.GetString("INFORME_DISCREPANCIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Plan Anual de Auditorías:.
        /// </summary>
        internal static string PLAN_ANUAL_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLAN_ANUAL_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Plan Anual de Auditorías:.
        /// </summary>
        internal static string PLAN_ANUAL_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLAN_ANUAL_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Planes Anuales de Auditorías:.
        /// </summary>
        internal static string PLAN_ANUAL_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLAN_ANUAL_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos del Acta del Comité de Calidad.
        /// </summary>
        internal static string PUNTOS_ACTAS_TITLE {
            get {
                return ResourceManager.GetString("PUNTOS_ACTAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Revisión:.
        /// </summary>
        internal static string REVISION_ADD_TITLE {
            get {
                return ResourceManager.GetString("REVISION_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Revisión:.
        /// </summary>
        internal static string REVISION_EDIT_TITLE {
            get {
                return ResourceManager.GetString("REVISION_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisiones:.
        /// </summary>
        internal static string REVISION_TITLE {
            get {
                return ResourceManager.GetString("REVISION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Auditorías:.
        /// </summary>
        internal static string TIPO_AUDITORIA_TITLE {
            get {
                return ResourceManager.GetString("TIPO_AUDITORIA_TITLE", resourceCulture);
            }
        }
    }
}
