//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Quality.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Quality.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoría: {0}{1}
        ///Fecha prevista de auditoría: {2}
        ///Áreas a auditar: {3}
        ///Auditor Responsable: {4}
        ///Otros:.
        /// </summary>
        public static string ASUNTO_COMUNICADO_AUDITORIA {
            get {
                return ResourceManager.GetString("ASUNTO_COMUNICADO_AUDITORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La auditoría ha sido aprobada..
        /// </summary>
        public static string AUDITORIA_APROBADA {
            get {
                return ResourceManager.GetString("AUDITORIA_APROBADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si cancela se perderán los últimos cambios realizados.
        ///                               ¿Cancelar?.
        /// </summary>
        public static string CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clase que está intentando borrar ya ha sigo asignada en algún horario..
        /// </summary>
        public static string CLASE_ASIGNADA {
            get {
                return ResourceManager.GetString("CLASE_ASIGNADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Reunión del Comité de Calidad correspondiente al mes de (MES de AÑO) se determinó notificar la ejecución de la Auditoría Nº {0} _({1}) {2}.
        ///Una vez analizada por los componentes del Comité, se le adjunta el informe correspondiente de la misma, para que tome las acciones correctoras adecuadas, así como formule las aclaraciones que considere efectivas para su desarrollo..
        /// </summary>
        public static string COMENTARIOS_COMUNICADO_NOTIFICACION_DISCREPANCIAS {
            get {
                return ResourceManager.GetString("COMENTARIOS_COMUNICADO_NOTIFICACION_DISCREPANCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se le informa del cierre de discrepancias de la auditoría {0} {1} {2}..
        /// </summary>
        public static string COMENTARIOS_NOTIFICACION_CIERRE_DISCREPANCIAS {
            get {
                return ResourceManager.GetString("COMENTARIOS_NOTIFICACION_CIERRE_DISCREPANCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La concesión de la ampliación ha sido notificada con éxito..
        /// </summary>
        public static string CONCESION_AUDITORIA_NOTIFICADA {
            get {
                return ResourceManager.GetString("CONCESION_AUDITORIA_NOTIFICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un elemento de esta entidad que está siendo editado. Para editar otro, por favor, cierre el anterior..
        /// </summary>
        public static string CURRENT_EDITION {
            get {
                return ResourceManager.GetString("CURRENT_EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay elementos en edición ¿Está seguro de que desea cerrar?.
        /// </summary>
        public static string CURRENT_EDITION_CLOSE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el elemento. Está siendo editado.
        /// </summary>
        public static string CURRENT_EDITION_DELETE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Confirmar la eliminación del elemento seleccionado?.
        /// </summary>
        public static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El borrado total de una empresa puede tardar algunos minutos.
        ///      ¿Confirmar la eliminación de la empresa seleccionada?.
        /// </summary>
        public static string DELETE_CONFIRM_EMPRESA {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La denegación de la ampliación ha sido notificada con éxito..
        /// </summary>
        public static string DENEGACION_AUDITORIA_NOTIFICADA {
            get {
                return ResourceManager.GetString("DENEGACION_AUDITORIA_NOTIFICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando actualización....
        /// </summary>
        public static string DOWNLOADING_DATA {
            get {
                return ResourceManager.GetString("DOWNLOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia de seguridad generada con éxito.
        /// </summary>
        public static string DUMP_OK {
            get {
                return ResourceManager.GetString("DUMP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando copia de seguridad....
        /// </summary>
        public static string DUMPING_BACKUP {
            get {
                return ResourceManager.GetString("DUMPING_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe otro elemento con ese códígo..
        /// </summary>
        public static string DUPLICATED_CODE {
            get {
                return ResourceManager.GetString("DUPLICATED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar la empresa activa..
        /// </summary>
        public static string EMPRESA_NEEDED {
            get {
                return ResourceManager.GetString("EMPRESA_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe vacío.
        /// </summary>
        public static string EMPTY_REPORT {
            get {
                return ResourceManager.GetString("EMPTY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string ENTERPRISE_MAX_LIMITED {
            get {
                return ResourceManager.GetString("ENTERPRISE_MAX_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de empresas de la aplicación ha alcanzado el límite permitido..
        /// </summary>
        public static string ENTERPRISE_MAX_LIMITED_NOTICE {
            get {
                return ResourceManager.GetString("ENTERPRISE_MAX_LIMITED_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado para acceder a esta empresa.
        /// </summary>
        public static string ENTERPRISE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ENTERPRISE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede llevar a cabo la acción seleccionada si el examen aún no ha sido emitido.
        /// </summary>
        public static string EXAMEN_NO_EMITIDO {
            get {
                return ResourceManager.GetString("EXAMEN_NO_EMITIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para acceder a las preguntas debe primero cerrar la ventana de edición de exámenes..
        /// </summary>
        public static string EXAMENES_MNG_OPEN {
            get {
                return ResourceManager.GetString("EXAMENES_MNG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el informe de ampliación {0}..
        /// </summary>
        public static string INFORME_AMPLIACION_MODIFICADO {
            get {
                return ResourceManager.GetString("INFORME_AMPLIACION_MODIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el informe de correcciones {0}..
        /// </summary>
        public static string INFORME_CORRECCIONES_MODIFICADO {
            get {
                return ResourceManager.GetString("INFORME_CORRECCIONES_MODIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El informe de acciones correctoras ha sido notificado con éxito..
        /// </summary>
        public static string INFORME_CORRECTOR_NOTIFICADO {
            get {
                return ResourceManager.GetString("INFORME_CORRECTOR_NOTIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el informe de discrepancia {0}..
        /// </summary>
        public static string INFORME_DISCREPANCIA_MODIFICADO {
            get {
                return ResourceManager.GetString("INFORME_DISCREPANCIA_MODIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El informe de discrepancias ha sido notificado con éxito..
        /// </summary>
        public static string INFORME_DISCREPANCIAS_NOTIFICADO {
            get {
                return ResourceManager.GetString("INFORME_DISCREPANCIAS_NOTIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;{0}&quot; contiene datos no válidos..
        /// </summary>
        public static string INVALID_FIELD_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FIELD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo modificado contiene datos no válidos..
        /// </summary>
        public static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando datos....
        /// </summary>
        public static string LOADING_DATA {
            get {
                return ResourceManager.GetString("LOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible bloquear el elemento seleccionado.
        ///Otro usuario está modificándolo en este momento. .
        /// </summary>
        public static string LOCK_ERROR {
            get {
                return ResourceManager.GetString("LOCK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error autentificando al usuario. Revise nombre de usuario y contraseña..
        /// </summary>
        public static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha seleccionado ningun cliente..
        /// </summary>
        public static string NO_CLIENT_SELECTED {
            get {
                return ResourceManager.GetString("NO_CLIENT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos disponibles para realizar una selección específica para este tipo de informe..
        /// </summary>
        public static string NO_DATA_ENTITY {
            get {
                return ResourceManager.GetString("NO_DATA_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos para imprimir..
        /// </summary>
        public static string NO_DATA_REPORTS {
            get {
                return ResourceManager.GetString("NO_DATA_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actual no puede ser eliminado.
        /// </summary>
        public static string NO_DELETE_USER {
            get {
                return ResourceManager.GetString("NO_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado elementos coincidentes.
        /// </summary>
        public static string NO_RESULTS {
            get {
                return ResourceManager.GetString("NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un elemento de la lista.
        /// </summary>
        public static string NO_SELECTED {
            get {
                return ResourceManager.GetString("NO_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible realizar la acción solicitada ({0}) sobre una auditoría en estado {1}..
        /// </summary>
        public static string NOT_ENABLED_ACTION {
            get {
                return ResourceManager.GetString("NOT_ENABLED_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede modificar el campo {0} de una auditoría en estado {1}..
        /// </summary>
        public static string NOT_ENABLED_PROPERTY {
            get {
                return ResourceManager.GetString("NOT_ENABLED_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas introducidas no son iguales.
        /// </summary>
        public static string NOT_EQUAL_PASS {
            get {
                return ResourceManager.GetString("NOT_EQUAL_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDITORÍAS CON DISCREPANCIAS BLOQUEADAS A {0}.
        /// </summary>
        public static string NOTIFY_AUDITORIA_DISCREPANCIAS_ABIERTAS {
            get {
                return ResourceManager.GetString("NOTIFY_AUDITORIA_DISCREPANCIAS_ABIERTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible realizar la operación.
        ///.
        /// </summary>
        public static string OPERATION_ERROR {
            get {
                return ResourceManager.GetString("OPERATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha escrito una contraseña. ¿Está seguro de que desea que el usuario no posea contraseña?.
        /// </summary>
        public static string PASSWORD_NULL {
            get {
                return ResourceManager.GetString("PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible borrar el Plan seleccionado mientras tenga Tipos de Auditoría asociados..
        /// </summary>
        public static string PLAN_ANUAL_CON_TIPOS_ASOCIADOS {
            get {
                return ResourceManager.GetString("PLAN_ANUAL_CON_TIPOS_ASOCIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los tipos de auditorías asociados al plan está incompleto. Por favor, compruebe que se han rellenado todos los datos..
        /// </summary>
        public static string PLAN_TIPO_NO_VALIDO {
            get {
                return ResourceManager.GetString("PLAN_TIPO_NO_VALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pregunta número {0} ha sido reservada por otro usuario. 
        ///Para poder guardar el examen debe eliminarla del mismo..
        /// </summary>
        public static string PREGUNTA_INCLUIDA {
            get {
                return ResourceManager.GetString("PREGUNTA_INCLUIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pregunta actual está incluída en algún examen que aún no ha sido emitido. 
        ///No será posible marcarla como inactiva hasta que no deje de estar reservada..
        /// </summary>
        public static string PREGUNTA_RESERVADA {
            get {
                return ResourceManager.GetString("PREGUNTA_RESERVADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las siguientes preguntas están inactivas y no podrán aparecer en el examen: {0}.
        ///Actívelas si desea que aparezcan en el mismo..
        /// </summary>
        public static string PREGUNTAS_INACTIVAS {
            get {
                return ResourceManager.GetString("PREGUNTAS_INACTIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para acceder a los exámenes debe primero cerrar la ventana de edición de preguntas..
        /// </summary>
        public static string PREGUNTAS_MNG_OPEN {
            get {
                return ResourceManager.GetString("PREGUNTAS_MNG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado para llevar a cabo la acción seleccionada..
        /// </summary>
        public static string RESTORE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("RESTORE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando....
        /// </summary>
        public static string SAVING {
            get {
                return ResourceManager.GetString("SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de ampliación ha sido notificada con éxito..
        /// </summary>
        public static string SOLICITUD_AMPLIACION_NOTIFICADA {
            get {
                return ResourceManager.GetString("SOLICITUD_AMPLIACION_NOTIFICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + = Agregar.
        /// </summary>
        public static string STATUS_GENERICO {
            get {
                return ResourceManager.GetString("STATUS_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando permisos....
        /// </summary>
        public static string VALIDATION_MSG {
            get {
                return ResourceManager.GetString("VALIDATION_MSG", resourceCulture);
            }
        }
    }
}
